<template>
    <div class="icon-wrapper">
        <Dropdown :trigger="disabled ? 'click' : 'hover'" @on-click="onClick" :transfer="transfer" style="width: 110px;float: left">
            <div style="width: 100%">
                <Button style="width: 100%" :disabled="disabled">
                    {{model}}
                    <Icon type="ios-arrow-down" v-if="!disabled"></Icon>
                </Button>
            </div>
            <DropdownMenu slot="list" v-for="(item, index) in items" :key="index">
                <DropdownItem :name="item.name" :key="item.name">{{item.value}}</DropdownItem>
            </DropdownMenu>
        </Dropdown>
        <Dropdown :trigger="disabled ? '' : 'click'" placement="bottom-start" transfer-class-name="icon-drop-wrapper" :transfer="transfer" class="icon-input">
            <div class="ivu-btn ivu-btn-default" style="width: 100%;position: relative" :disabled="disabled">
                <span style="position: absolute;left: 0;top: 5px" v-if="model=='icon'">
                    <Icon v-for="item in selectItem" :type="item.type" style="width: 30px;height: 30px" size="18"/>
                </span>
                <span style="position: absolute;left: 0;top: 5px" v-if="model=='icon-font'">
                    <Icon v-for="item in selectItem" :custom="item.type" style="width: 30px;height: 30px" size="16"/>
                </span>
                <span style="position: absolute;left: 0;top: 5px" v-if="model=='svg'">
                    <span v-for="(item, index) in selectItem" :key="index">
                        <svg class="icon-svg-wrapper" aria-hidden="true">
                            <use :xlink:href="item.before"></use>
                        </svg>
                        <svg class="icon-svg-wrapper" aria-hidden="true">
                            <use :xlink:href="item.after"></use>
                        </svg>
                    </span>
                </span>
            </div>
            <DropdownMenu slot="list">
            <div v-if="model=='icon'">
                <span v-for="item in iconDatas" @click="selectClick(item)">
                    <Icon :type="item.type" class="dropdown-span" style="width: 35px;height: 35px;line-height: 35px;" size="18"/>
                </span>
            </div>
            <div v-if="model=='icon-font'">
                <span v-for="item in iconFontDatas" @click="selectClick(item)">
                    <Icon :custom="item.type" class="dropdown-span" style="width: 35px;height: 35px;line-height: 35px;" size="16"/>
                </span>
            </div>
            <div v-if="model=='svg'">
                <div v-for="item in svgDatas" @click="selectClick(item)" class="svg-div">
                    <svg class="icon-svg-wrapper" aria-hidden="true">
                        <use :xlink:href="item.before"></use>
                    </svg>
                    <svg class="icon-svg-wrapper" aria-hidden="true" v-if="item.after != ''">
                        <use :xlink:href="item.after"></use>
                    </svg>
                </div>
            </div>
            <div v-if="model=='img'">
                <span style="margin-left: 5px;color: #808695">{{$t('bmsa.baise.noMessage')}}</span>
            </div>
            </DropdownMenu>
        </Dropdown>
    </div>
</template>
<script>
    export default {
        name: 'bingo-select-icon',
        data () {
            return {
                model: '',
                items: [
                    {
                        name: 'icon',
                        value: 'icon'
                    },
                    {
                        name: 'icon-font',
                        value: 'icon-font'
                    },
                    {
                        name: 'svg',
                        value: 'svg'
                    },
                    {
                        name: 'img',
                        value: 'img'
                    }
                ],
                selectItem: [],
                iconDatas: [
                    {type: 'ios-add'},
                    {type: 'ios-add-circle'},
                    {type: 'ios-add-circle-outline'},
                    {type: 'ios-alarm'},
                    {type: 'ios-alarm-outline'},
                    {type: 'ios-albums'},
                    {type: 'ios-albums-outline'},
                    {type: 'ios-alert'},
                    {type: 'ios-alert-outline'},
                    {type: 'ios-american-football'},
                    {type: 'ios-american-football-outline'},
                    {type: 'ios-analytics'},
                    {type: 'ios-analytics-outline'},
                    {type: 'ios-aperture'},
                    {type: 'ios-aperture-outline'},
                    {type: 'ios-apps'},
                    {type: 'ios-apps-outline'},
                    {type: 'ios-appstore'},
                    {type: 'ios-appstore-outline'},
                    {type: 'ios-archive'},
                    {type: 'ios-archive-outline'},
                    {type: 'ios-arrow-back'},
                    {type: 'ios-arrow-down'},
                    {type: 'ios-arrow-dropdown'},
                    {type: 'ios-arrow-dropdown-circle'},
                    {type: 'ios-arrow-dropleft'},
                    {type: 'ios-arrow-dropleft-circle'},
                    {type: 'ios-arrow-dropright'},
                    {type: 'ios-arrow-dropright-circle'},
                    {type: 'ios-arrow-dropup'},
                    {type: 'ios-arrow-dropup-circle'},
                    {type: 'ios-arrow-forward'},
                    {type: 'ios-arrow-round-back'},
                    {type: 'ios-arrow-round-down'},
                    {type: 'ios-arrow-round-forward'},
                    {type: 'ios-arrow-round-up'},
                    {type: 'ios-arrow-up'},
                    {type: 'ios-at'},
                    {type: 'ios-at-outline'},
                    {type: 'ios-attach'},
                    {type: 'ios-backspace'},
                    {type: 'ios-backspace-outline'},
                    {type: 'ios-barcode'},
                    {type: 'ios-barcode-outline'},
                    {type: 'ios-baseball'},
                    {type: 'ios-baseball-outline'},
                    {type: 'ios-basket'},
                    {type: 'ios-basket-outline'},
                    {type: 'ios-basketball'},
                    {type: 'ios-basketball-outline'},
                    {type: 'ios-battery-charging'},
                    {type: 'ios-battery-dead'},
                    {type: 'ios-battery-full'},
                    {type: 'ios-beaker'},
                    {type: 'ios-beaker-outline'},
                    {type: 'ios-beer'},
                    {type: 'ios-beer-outline'},
                    {type: 'ios-bicycle'},
                    {type: 'ios-bluetooth'},
                    {type: 'ios-boat'},
                    {type: 'ios-boat-outline'},
                    {type: 'ios-body'},
                    {type: 'ios-body-outline'},
                    {type: 'ios-bonfire'},
                    {type: 'ios-bonfire-outline'},
                    {type: 'ios-book'},
                    {type: 'ios-book-outline'},
                    {type: 'ios-bookmark'},
                    {type: 'ios-bookmark-outline'},
                    {type: 'ios-bookmarks'},
                    {type: 'ios-bookmarks-outline'},
                    {type: 'ios-bowtie'},
                    {type: 'ios-bowtie-outline'},
                    {type: 'ios-briefcase'},
                    {type: 'ios-briefcase-outline'},
                    {type: 'ios-browsers'},
                    {type: 'ios-browsers-outline'},
                    {type: 'ios-brush'},
                    {type: 'ios-brush-outline'},
                    {type: 'ios-bug'},
                    {type: 'ios-bug-outline'},
                    {type: 'ios-build'},
                    {type: 'ios-build-outline'},
                    {type: 'ios-bulb'},
                    {type: 'ios-bulb-outline'},
                    {type: 'ios-bus'},
                    {type: 'ios-bus-outline'},
                    {type: 'ios-cafe'},
                    {type: 'ios-cafe-outline'},
                    {type: 'ios-calculator'},
                    {type: 'ios-calculator-outline'},
                    {type: 'ios-calendar'},
                    {type: 'ios-calendar-outline'},
                    {type: 'ios-call'},
                    {type: 'ios-call-outline'},
                    {type: 'ios-camera'},
                    {type: 'ios-camera-outline'},
                    {type: 'ios-car'},
                    {type: 'ios-car-outline'},
                    {type: 'ios-card'},
                    {type: 'ios-card-outline'},
                    {type: 'ios-cart'},
                    {type: 'ios-cart-outline'},
                    {type: 'ios-cash'},
                    {type: 'ios-cash-outline'},
                    {type: 'ios-chatboxes'},
                    {type: 'ios-chatboxes-outline'},
                    {type: 'ios-chatbubbles'},
                    {type: 'ios-chatbubbles-outline'},
                    {type: 'ios-checkbox'},
                    {type: 'ios-checkbox-outline'},
                    {type: 'ios-checkmark'},
                    {type: 'ios-checkmark-circle'},
                    {type: 'ios-checkmark-circle-outline'},
                    {type: 'ios-clipboard'},
                    {type: 'ios-clipboard-outline'},
                    {type: 'ios-clock'},
                    {type: 'ios-clock-outline'},
                    {type: 'ios-close'},
                    {type: 'ios-close-circle'},
                    {type: 'ios-close-circle-outline'},
                    {type: 'ios-closed-captioning'},
                    {type: 'ios-closed-captioning-outline'},
                    {type: 'ios-cloud'},
                    {type: 'ios-cloud-circle'},
                    {type: 'ios-cloud-circle-outline'},
                    {type: 'ios-cloud-done'},
                    {type: 'ios-cloud-done-outline'},
                    {type: 'ios-cloud-download'},
                    {type: 'ios-cloud-download-outline'},
                    {type: 'ios-cloud-outline'},
                    {type: 'ios-cloud-upload'},
                    {type: 'ios-cloud-upload-outline'},
                    {type: 'ios-cloudy'},
                    {type: 'ios-cloudy-night'},
                    {type: 'ios-cloudy-night-outline'},
                    {type: 'ios-cloudy-outline'},
                    {type: 'ios-code'},
                    {type: 'ios-code-download'},
                    {type: 'ios-code-working'},
                    {type: 'ios-cog'},
                    {type: 'ios-cog-outline'},
                    {type: 'ios-color-fill'},
                    {type: 'ios-color-fill-outline'},
                    {type: 'ios-color-filter'},
                    {type: 'ios-color-filter-outline'},
                    {type: 'ios-color-palette'},
                    {type: 'ios-color-palette-outline'},
                    {type: 'ios-color-wand'},
                    {type: 'ios-color-wand-outline'},
                    {type: 'ios-compass'},
                    {type: 'ios-compass-outline'},
                    {type: 'ios-construct'},
                    {type: 'ios-construct-outline'},
                    {type: 'ios-contact'},
                    {type: 'ios-contact-outline'},
                    {type: 'ios-contacts'},
                    {type: 'ios-contacts-outline'},
                    {type: 'ios-contract'},
                    {type: 'ios-contrast'},
                    {type: 'ios-copy'},
                    {type: 'ios-copy-outline'},
                    {type: 'ios-create'},
                    {type: 'ios-create-outline'},
                    {type: 'ios-crop'},
                    {type: 'ios-crop-outline'},
                    {type: 'ios-cube'},
                    {type: 'ios-cube-outline'},
                    {type: 'ios-cut'},
                    {type: 'ios-cut-outline'},
                    {type: 'ios-desktop'},
                    {type: 'ios-desktop-outline'},
                    {type: 'ios-disc'},
                    {type: 'ios-disc-outline'},
                    {type: 'ios-document'},
                    {type: 'ios-document-outline'},
                    {type: 'ios-done-all'},
                    {type: 'ios-download'},
                    {type: 'ios-download-outline'},
                    {type: 'ios-easel'},
                    {type: 'ios-easel-outline'},
                    {type: 'ios-egg'},
                    {type: 'ios-egg-outline'},
                    {type: 'ios-exit'},
                    {type: 'ios-exit-outline'},
                    {type: 'ios-expand'},
                    {type: 'ios-eye'},
                    {type: 'ios-eye-off'},
                    {type: 'ios-eye-off-outline'},
                    {type: 'ios-eye-outline'},
                    {type: 'ios-fastforward'},
                    {type: 'ios-fastforward-outline'},
                    {type: 'ios-female'},
                    {type: 'ios-filing'},
                    {type: 'ios-filing-outline'},
                    {type: 'ios-film'},
                    {type: 'ios-film-outline'},
                    {type: 'ios-finger-print'},
                    {type: 'ios-flag'},
                    {type: 'ios-flag-outline'},
                    {type: 'ios-flame'},
                    {type: 'ios-flame-outline'},
                    {type: 'ios-flash'},
                    {type: 'ios-flash-outline'},
                    {type: 'ios-flask'},
                    {type: 'ios-flask-outline'},
                    {type: 'ios-flower'},
                    {type: 'ios-flower-outline'},
                    {type: 'ios-folder'},
                    {type: 'ios-folder-open'},
                    {type: 'ios-folder-open-outline'},
                    {type: 'ios-folder-outline'},
                    {type: 'ios-football'},
                    {type: 'ios-football-outline'},
                    {type: 'ios-funnel'},
                    {type: 'ios-funnel-outline'},
                    {type: 'ios-game-controller-a'},
                    {type: 'ios-game-controller-a-outline'},
                    {type: 'ios-game-controller-b'},
                    {type: 'ios-game-controller-b-outline'},
                    {type: 'ios-git-branch'},
                    {type: 'ios-git-commit'},
                    {type: 'ios-git-compare'},
                    {type: 'ios-git-merge'},
                    {type: 'ios-git-network'},
                    {type: 'ios-git-pull-request'},
                    {type: 'ios-glasses'},
                    {type: 'ios-glasses-outline'},
                    {type: 'ios-globe'},
                    {type: 'ios-globe-outline'},
                    {type: 'ios-grid'},
                    {type: 'ios-grid-outline'},
                    {type: 'ios-hammer'},
                    {type: 'ios-hammer-outline'},
                    {type: 'ios-hand'},
                    {type: 'ios-hand-outline'},
                    {type: 'ios-happy'},
                    {type: 'ios-happy-outline'},
                    {type: 'ios-headset'},
                    {type: 'ios-headset-outline'},
                    {type: 'ios-heart'},
                    {type: 'ios-heart-outline'},
                    {type: 'ios-help'},
                    {type: 'ios-help-buoy'},
                    {type: 'ios-help-buoy-outline'},
                    {type: 'ios-help-circle'},
                    {type: 'ios-help-circle-outline'},
                    {type: 'ios-home'},
                    {type: 'ios-home-outline'},
                    {type: 'ios-ice-cream'},
                    {type: 'ios-ice-cream-outline'},
                    {type: 'ios-image'},
                    {type: 'ios-image-outline'},
                    {type: 'ios-images'},
                    {type: 'ios-images-outline'},
                    {type: 'ios-infinite'},
                    {type: 'ios-infinite-outline'},
                    {type: 'ios-information'},
                    {type: 'ios-information-circle'},
                    {type: 'ios-information-circle-outline'},
                    {type: 'ios-ionic'},
                    {type: 'ios-ionic-outline'},
                    {type: 'ios-ionitron'},
                    {type: 'ios-ionitron-outline'},
                    {type: 'ios-jet'},
                    {type: 'ios-jet-outline'},
                    {type: 'ios-key'},
                    {type: 'ios-key-outline'},
                    {type: 'ios-keypad'},
                    {type: 'ios-keypad-outline'},
                    {type: 'ios-laptop'},
                    {type: 'ios-leaf'},
                    {type: 'ios-leaf-outline'},
                    {type: 'ios-link'},
                    {type: 'ios-link-outline'},
                    {type: 'ios-list'},
                    {type: 'ios-list-box'},
                    {type: 'ios-list-box-outline'},
                    {type: 'ios-loading'},
                    {type: 'ios-locate'},
                    {type: 'ios-locate-outline'},
                    {type: 'ios-lock'},
                    {type: 'ios-lock-outline'},
                    {type: 'ios-log-in'},
                    {type: 'ios-log-out'},
                    {type: 'ios-magnet'},
                    {type: 'ios-magnet-outline'},
                    {type: 'ios-mail'},
                    {type: 'ios-mail-open'},
                    {type: 'ios-mail-open-outline'},
                    {type: 'ios-mail-outline'},
                    {type: 'ios-male'},
                    {type: 'ios-man'},
                    {type: 'ios-man-outline'},
                    {type: 'ios-map'},
                    {type: 'ios-map-outline'},
                    {type: 'ios-medal'},
                    {type: 'ios-medal-outline'},
                    {type: 'ios-medical'},
                    {type: 'ios-medical-outline'},
                    {type: 'ios-medkit'},
                    {type: 'ios-medkit-outline'},
                    {type: 'ios-megaphone'},
                    {type: 'ios-megaphone-outline'},
                    {type: 'ios-menu'},
                    {type: 'ios-menu-outline'},
                    {type: 'ios-mic'},
                    {type: 'ios-mic-off'},
                    {type: 'ios-mic-off-outline'},
                    {type: 'ios-mic-outline'},
                    {type: 'ios-microphone'},
                    {type: 'ios-microphone-outline'},
                    {type: 'ios-moon'},
                    {type: 'ios-moon-outline'},
                    {type: 'ios-more'},
                    {type: 'ios-more-outline'},
                    {type: 'ios-move'},
                    {type: 'ios-musical-note'},
                    {type: 'ios-musical-note-outline'},
                    {type: 'ios-musical-notes'},
                    {type: 'ios-musical-notes-outline'},
                    {type: 'ios-navigate'},
                    {type: 'ios-navigate-outline'},
                    {type: 'ios-no-smoking'},
                    {type: 'ios-no-smoking-outline'},
                    {type: 'ios-notifications'},
                    {type: 'ios-notifications-off'},
                    {type: 'ios-notifications-off-outline'},
                    {type: 'ios-notifications-outline'},
                    {type: 'ios-nuclear'},
                    {type: 'ios-nuclear-outline'},
                    {type: 'ios-nutrition'},
                    {type: 'ios-nutrition-outline'},
                    {type: 'ios-open'},
                    {type: 'ios-open-outline'},
                    {type: 'ios-options'},
                    {type: 'ios-options-outline'},
                    {type: 'ios-outlet'},
                    {type: 'ios-outlet-outline'},
                    {type: 'ios-paper'},
                    {type: 'ios-paper-outline'},
                    {type: 'ios-paper-plane'},
                    {type: 'ios-paper-plane-outline'},
                    {type: 'ios-partly-sunny'},
                    {type: 'ios-partly-sunny-outline'},
                    {type: 'ios-pause'},
                    {type: 'ios-pause-outline'},
                    {type: 'ios-paw'},
                    {type: 'ios-paw-outline'},
                    {type: 'ios-people'},
                    {type: 'ios-people-outline'},
                    {type: 'ios-person'},
                    {type: 'ios-person-add'},
                    {type: 'ios-person-add-outline'},
                    {type: 'ios-person-outline'},
                    {type: 'ios-phone-landscape'},
                    {type: 'ios-phone-portrait'},
                    {type: 'ios-photos'},
                    {type: 'ios-photos-outline'},
                    {type: 'ios-pie'},
                    {type: 'ios-pie-outline'},
                    {type: 'ios-pin'},
                    {type: 'ios-pin-outline'},
                    {type: 'ios-pint'},
                    {type: 'ios-pint-outline'},
                    {type: 'ios-pizza'},
                    {type: 'ios-pizza-outline'},
                    {type: 'ios-plane'},
                    {type: 'ios-plane-outline'},
                    {type: 'ios-planet'},
                    {type: 'ios-planet-outline'},
                    {type: 'ios-play'},
                    {type: 'ios-play-outline'},
                    {type: 'ios-podium'},
                    {type: 'ios-podium-outline'},
                    {type: 'ios-power'},
                    {type: 'ios-power-outline'},
                    {type: 'ios-pricetag'},
                    {type: 'ios-pricetag-outline'},
                    {type: 'ios-pricetags'},
                    {type: 'ios-pricetags-outline'},
                    {type: 'ios-print'},
                    {type: 'ios-print-outline'},
                    {type: 'ios-pulse'},
                    {type: 'ios-pulse-outline'},
                    {type: 'ios-qr-scanner'},
                    {type: 'ios-quote'},
                    {type: 'ios-quote-outline'},
                    {type: 'ios-radio'},
                    {type: 'ios-radio-button-off'},
                    {type: 'ios-radio-button-on'},
                    {type: 'ios-radio-outline'},
                    {type: 'ios-rainy'},
                    {type: 'ios-rainy-outline'},
                    {type: 'ios-recording'},
                    {type: 'ios-recording-outline'},
                    {type: 'ios-redo'},
                    {type: 'ios-redo-outline'},
                    {type: 'ios-refresh'},
                    {type: 'ios-refresh-circle'},
                    {type: 'ios-refresh-circle-outline'},
                    {type: 'ios-remove'},
                    {type: 'ios-remove-circle'},
                    {type: 'ios-remove-circle-outline'},
                    {type: 'ios-reorder'},
                    {type: 'ios-repeat'},
                    {type: 'ios-resize'},
                    {type: 'ios-restaurant'},
                    {type: 'ios-restaurant-outline'},
                    {type: 'ios-return-left'},
                    {type: 'ios-return-right'},
                    {type: 'ios-reverse-camera'},
                    {type: 'ios-reverse-camera-outline'},
                    {type: 'ios-rewind'},
                    {type: 'ios-rewind-outline'},
                    {type: 'ios-ribbon'},
                    {type: 'ios-ribbon-outline'},
                    {type: 'ios-rose'},
                    {type: 'ios-rose-outline'},
                    {type: 'ios-sad'},
                    {type: 'ios-sad-outline'},
                    {type: 'ios-school'},
                    {type: 'ios-school-outline'},
                    {type: 'ios-search'},
                    {type: 'ios-search-outline'},
                    {type: 'ios-send'},
                    {type: 'ios-send-outline'},
                    {type: 'ios-settings'},
                    {type: 'ios-settings-outline'},
                    {type: 'ios-share'},
                    {type: 'ios-share-alt'},
                    {type: 'ios-share-alt-outline'},
                    {type: 'ios-share-outline'},
                    {type: 'ios-shirt'},
                    {type: 'ios-shirt-outline'},
                    {type: 'ios-shuffle'},
                    {type: 'ios-skip-backward'},
                    {type: 'ios-skip-backward-outline'},
                    {type: 'ios-skip-forward'},
                    {type: 'ios-skip-forward-outline'},
                    {type: 'ios-snow'},
                    {type: 'ios-snow-outline'},
                    {type: 'ios-speedometer'},
                    {type: 'ios-speedometer-outline'},
                    {type: 'ios-square'},
                    {type: 'ios-square-outline'},
                    {type: 'ios-star'},
                    {type: 'ios-star-half'},
                    {type: 'ios-star-outline'},
                    {type: 'ios-stats'},
                    {type: 'ios-stats-outline'},
                    {type: 'ios-stopwatch'},
                    {type: 'ios-stopwatch-outline'},
                    {type: 'ios-subway'},
                    {type: 'ios-subway-outline'},
                    {type: 'ios-sunny'},
                    {type: 'ios-sunny-outline'},
                    {type: 'ios-swap'},
                    {type: 'ios-switch'},
                    {type: 'ios-switch-outline'},
                    {type: 'ios-sync'},
                    {type: 'ios-tablet-landscape'},
                    {type: 'ios-tablet-portrait'},
                    {type: 'ios-tennisball'},
                    {type: 'ios-tennisball-outline'},
                    {type: 'ios-text'},
                    {type: 'ios-text-outline'},
                    {type: 'ios-thermometer'},
                    {type: 'ios-thermometer-outline'},
                    {type: 'ios-thumbs-down'},
                    {type: 'ios-thumbs-down-outline'},
                    {type: 'ios-thumbs-up'},
                    {type: 'ios-thumbs-up-outline'},
                    {type: 'ios-thunderstorm'},
                    {type: 'ios-thunderstorm-outline'},
                    {type: 'ios-time'},
                    {type: 'ios-time-outline'},
                    {type: 'ios-timer'},
                    {type: 'ios-timer-outline'},
                    {type: 'ios-train'},
                    {type: 'ios-train-outline'},
                    {type: 'ios-transgender'},
                    {type: 'ios-trash'},
                    {type: 'ios-trash-outline'},
                    {type: 'ios-trending-down'},
                    {type: 'ios-trending-up'},
                    {type: 'ios-trophy'},
                    {type: 'ios-trophy-outline'},
                    {type: 'ios-umbrella'},
                    {type: 'ios-umbrella-outline'},
                    {type: 'ios-undo'},
                    {type: 'ios-undo-outline'},
                    {type: 'ios-unlock'},
                    {type: 'ios-unlock-outline'},
                    {type: 'ios-videocam'},
                    {type: 'ios-videocam-outline'},
                    {type: 'ios-volume-down'},
                    {type: 'ios-volume-mute'},
                    {type: 'ios-volume-off'},
                    {type: 'ios-volume-up'},
                    {type: 'ios-walk'},
                    {type: 'ios-warning'},
                    {type: 'ios-warning-outline'},
                    {type: 'ios-watch'},
                    {type: 'ios-water'},
                    {type: 'ios-water-outline'},
                    {type: 'ios-wifi'},
                    {type: 'ios-wifi-outline'},
                    {type: 'ios-wine'},
                    {type: 'ios-wine-outline'},
                    {type: 'ios-woman'},
                    {type: 'ios-woman-outline'},
                    {type: 'logo-android'},
                    {type: 'logo-angular'},
                    {type: 'logo-apple'},
                    {type: 'logo-bitcoin'},
                    {type: 'logo-buffer'},
                    {type: 'logo-chrome'},
                    {type: 'logo-codepen'},
                    {type: 'logo-css3'},
                    {type: 'logo-designernews'},
                    {type: 'logo-dribbble'},
                    {type: 'logo-dropbox'},
                    {type: 'logo-euro'},
                    {type: 'logo-facebook'},
                    {type: 'logo-foursquare'},
                    {type: 'logo-freebsd-devil'},
                    {type: 'logo-github'},
                    {type: 'logo-google'},
                    {type: 'logo-googleplus'},
                    {type: 'logo-hackernews'},
                    {type: 'logo-html5'},
                    {type: 'logo-instagram'},
                    {type: 'logo-javascript'},
                    {type: 'logo-linkedin'},
                    {type: 'logo-markdown'},
                    {type: 'logo-nodejs'},
                    {type: 'logo-octocat'},
                    {type: 'logo-pinterest'},
                    {type: 'logo-playstation'},
                    {type: 'logo-python'},
                    {type: 'logo-reddit'},
                    {type: 'logo-rss'},
                    {type: 'logo-sass'},
                    {type: 'logo-skype'},
                    {type: 'logo-snapchat'},
                    {type: 'logo-steam'},
                    {type: 'logo-tumblr'},
                    {type: 'logo-tux'},
                    {type: 'logo-twitch'},
                    {type: 'logo-twitter'},
                    {type: 'logo-usd'},
                    {type: 'logo-vimeo'},
                    {type: 'logo-whatsapp'},
                    {type: 'logo-windows'},
                    {type: 'logo-wordpress'},
                    {type: 'logo-xbox'},
                    {type: 'logo-yahoo'},
                    {type: 'logo-yen'},
                    {type: 'logo-youtube'},
                    {type: 'md-add'},
                    {type: 'md-add-circle'},
                    {type: 'md-alarm'},
                    {type: 'md-albums'},
                    {type: 'md-alert'},
                    {type: 'md-american-football'},
                    {type: 'md-analytics'},
                    {type: 'md-aperture'},
                    {type: 'md-apps'},
                    {type: 'md-appstore'},
                    {type: 'md-archive'},
                    {type: 'md-arrow-back'},
                    {type: 'md-arrow-down'},
                    {type: 'md-arrow-dropdown'},
                    {type: 'md-arrow-dropdown-circle'},
                    {type: 'md-arrow-dropleft'},
                    {type: 'md-arrow-dropleft-circle'},
                    {type: 'md-arrow-dropright'},
                    {type: 'md-arrow-dropright-circle'},
                    {type: 'md-arrow-dropup'},
                    {type: 'md-arrow-dropup-circle'},
                    {type: 'md-arrow-forward'},
                    {type: 'md-arrow-round-back'},
                    {type: 'md-arrow-round-down'},
                    {type: 'md-arrow-round-forward'},
                    {type: 'md-arrow-round-up'},
                    {type: 'md-arrow-up'},
                    {type: 'md-at'},
                    {type: 'md-attach'},
                    {type: 'md-backspace'},
                    {type: 'md-barcode'},
                    {type: 'md-baseball'},
                    {type: 'md-basket'},
                    {type: 'md-basketball'},
                    {type: 'md-battery-charging'},
                    {type: 'md-battery-dead'},
                    {type: 'md-battery-full'},
                    {type: 'md-beaker'},
                    {type: 'md-beer'},
                    {type: 'md-bicycle'},
                    {type: 'md-bluetooth'},
                    {type: 'md-boat'},
                    {type: 'md-body'},
                    {type: 'md-bonfire'},
                    {type: 'md-book'},
                    {type: 'md-bookmark'},
                    {type: 'md-bookmarks'},
                    {type: 'md-bowtie'},
                    {type: 'md-briefcase'},
                    {type: 'md-browsers'},
                    {type: 'md-brush'},
                    {type: 'md-bug'},
                    {type: 'md-build'},
                    {type: 'md-bulb'},
                    {type: 'md-bus'},
                    {type: 'md-cafe'},
                    {type: 'md-calculator'},
                    {type: 'md-calendar'},
                    {type: 'md-call'},
                    {type: 'md-camera'},
                    {type: 'md-car'},
                    {type: 'md-card'},
                    {type: 'md-cart'},
                    {type: 'md-cash'},
                    {type: 'md-chatboxes'},
                    {type: 'md-chatbubbles'},
                    {type: 'md-checkbox'},
                    {type: 'md-checkbox-outline'},
                    {type: 'md-checkmark'},
                    {type: 'md-checkmark-circle'},
                    {type: 'md-checkmark-circle-outline'},
                    {type: 'md-clipboard'},
                    {type: 'md-clock'},
                    {type: 'md-close'},
                    {type: 'md-close-circle'},
                    {type: 'md-closed-captioning'},
                    {type: 'md-cloud'},
                    {type: 'md-cloud-circle'},
                    {type: 'md-cloud-done'},
                    {type: 'md-cloud-download'},
                    {type: 'md-cloud-outline'},
                    {type: 'md-cloud-upload'},
                    {type: 'md-cloudy'},
                    {type: 'md-cloudy-night'},
                    {type: 'md-code'},
                    {type: 'md-code-download'},
                    {type: 'md-code-working'},
                    {type: 'md-cog'},
                    {type: 'md-color-fill'},
                    {type: 'md-color-filter'},
                    {type: 'md-color-palette'},
                    {type: 'md-color-wand'},
                    {type: 'md-compass'},
                    {type: 'md-construct'},
                    {type: 'md-contact'},
                    {type: 'md-contacts'},
                    {type: 'md-contract'},
                    {type: 'md-contrast'},
                    {type: 'md-copy'},
                    {type: 'md-create'},
                    {type: 'md-crop'},
                    {type: 'md-cube'},
                    {type: 'md-cut'},
                    {type: 'md-desktop'},
                    {type: 'md-disc'},
                    {type: 'md-document'},
                    {type: 'md-done-all'},
                    {type: 'md-download'},
                    {type: 'md-easel'},
                    {type: 'md-egg'},
                    {type: 'md-exit'},
                    {type: 'md-expand'},
                    {type: 'md-eye'},
                    {type: 'md-eye-off'},
                    {type: 'md-fastforward'},
                    {type: 'md-female'},
                    {type: 'md-filing'},
                    {type: 'md-film'},
                    {type: 'md-finger-print'},
                    {type: 'md-flag'},
                    {type: 'md-flame'},
                    {type: 'md-flash'},
                    {type: 'md-flask'},
                    {type: 'md-flower'},
                    {type: 'md-folder'},
                    {type: 'md-folder-open'},
                    {type: 'md-football'},
                    {type: 'md-funnel'},
                    {type: 'md-game-controller-a'},
                    {type: 'md-game-controller-b'},
                    {type: 'md-git-branch'},
                    {type: 'md-git-commit'},
                    {type: 'md-git-compare'},
                    {type: 'md-git-merge'},
                    {type: 'md-git-network'},
                    {type: 'md-git-pull-request'},
                    {type: 'md-glasses'},
                    {type: 'md-globe'},
                    {type: 'md-grid'},
                    {type: 'md-hammer'},
                    {type: 'md-hand'},
                    {type: 'md-happy'},
                    {type: 'md-headset'},
                    {type: 'md-heart'},
                    {type: 'md-heart-outline'},
                    {type: 'md-help'},
                    {type: 'md-help-buoy'},
                    {type: 'md-help-circle'},
                    {type: 'md-home'},
                    {type: 'md-ice-cream'},
                    {type: 'md-image'},
                    {type: 'md-images'},
                    {type: 'md-infinite'},
                    {type: 'md-information'},
                    {type: 'md-information-circle'},
                    {type: 'md-ionic'},
                    {type: 'md-ionitron'},
                    {type: 'md-jet'},
                    {type: 'md-key'},
                    {type: 'md-keypad'},
                    {type: 'md-laptop'},
                    {type: 'md-leaf'},
                    {type: 'md-link'},
                    {type: 'md-list'},
                    {type: 'md-list-box'},
                    {type: 'md-locate'},
                    {type: 'md-lock'},
                    {type: 'md-log-in'},
                    {type: 'md-log-out'},
                    {type: 'md-magnet'},
                    {type: 'md-mail'},
                    {type: 'md-mail-open'},
                    {type: 'md-male'},
                    {type: 'md-man'},
                    {type: 'md-map'},
                    {type: 'md-medal'},
                    {type: 'md-medical'},
                    {type: 'md-medkit'},
                    {type: 'md-megaphone'},
                    {type: 'md-menu'},
                    {type: 'md-mic'},
                    {type: 'md-mic-off'},
                    {type: 'md-microphone'},
                    {type: 'md-moon'},
                    {type: 'md-more'},
                    {type: 'md-move'},
                    {type: 'md-musical-note'},
                    {type: 'md-musical-notes'},
                    {type: 'md-navigate'},
                    {type: 'md-no-smoking'},
                    {type: 'md-notifications'},
                    {type: 'md-notifications-off'},
                    {type: 'md-notifications-outline'},
                    {type: 'md-nuclear'},
                    {type: 'md-nutrition'},
                    {type: 'md-open'},
                    {type: 'md-options'},
                    {type: 'md-outlet'},
                    {type: 'md-paper'},
                    {type: 'md-paper-plane'},
                    {type: 'md-partly-sunny'},
                    {type: 'md-pause'},
                    {type: 'md-paw'},
                    {type: 'md-people'},
                    {type: 'md-person'},
                    {type: 'md-person-add'},
                    {type: 'md-phone-landscape'},
                    {type: 'md-phone-portrait'},
                    {type: 'md-photos'},
                    {type: 'md-pie'},
                    {type: 'md-pin'},
                    {type: 'md-pint'},
                    {type: 'md-pizza'},
                    {type: 'md-plane'},
                    {type: 'md-planet'},
                    {type: 'md-play'},
                    {type: 'md-podium'},
                    {type: 'md-power'},
                    {type: 'md-pricetag'},
                    {type: 'md-pricetags'},
                    {type: 'md-print'},
                    {type: 'md-pulse'},
                    {type: 'md-qr-scanner'},
                    {type: 'md-quote'},
                    {type: 'md-radio'},
                    {type: 'md-radio-button-off'},
                    {type: 'md-radio-button-on'},
                    {type: 'md-rainy'},
                    {type: 'md-recording'},
                    {type: 'md-redo'},
                    {type: 'md-refresh'},
                    {type: 'md-refresh-circle'},
                    {type: 'md-remove'},
                    {type: 'md-remove-circle'},
                    {type: 'md-reorder'},
                    {type: 'md-repeat'},
                    {type: 'md-resize'},
                    {type: 'md-restaurant'},
                    {type: 'md-return-left'},
                    {type: 'md-return-right'},
                    {type: 'md-reverse-camera'},
                    {type: 'md-rewind'},
                    {type: 'md-ribbon'},
                    {type: 'md-rose'},
                    {type: 'md-sad'},
                    {type: 'md-school'},
                    {type: 'md-search'},
                    {type: 'md-send'},
                    {type: 'md-settings'},
                    {type: 'md-share'},
                    {type: 'md-share-alt'},
                    {type: 'md-shirt'},
                    {type: 'md-shuffle'},
                    {type: 'md-skip-backward'},
                    {type: 'md-skip-forward'},
                    {type: 'md-snow'},
                    {type: 'md-speedometer'},
                    {type: 'md-square'},
                    {type: 'md-square-outline'},
                    {type: 'md-star'},
                    {type: 'md-star-half'},
                    {type: 'md-star-outline'},
                    {type: 'md-stats'},
                    {type: 'md-stopwatch'},
                    {type: 'md-subway'},
                    {type: 'md-sunny'},
                    {type: 'md-swap'},
                    {type: 'md-switch'},
                    {type: 'md-sync'},
                    {type: 'md-tablet-landscape'},
                    {type: 'md-tablet-portrait'},
                    {type: 'md-tennisball'},
                    {type: 'md-text'},
                    {type: 'md-thermometer'},
                    {type: 'md-thumbs-down'},
                    {type: 'md-thumbs-up'},
                    {type: 'md-thunderstorm'},
                    {type: 'md-time'},
                    {type: 'md-timer'},
                    {type: 'md-train'},
                    {type: 'md-transgender'},
                    {type: 'md-trash'},
                    {type: 'md-trending-down'},
                    {type: 'md-trending-up'},
                    {type: 'md-trophy'},
                    {type: 'md-umbrella'},
                    {type: 'md-undo'},
                    {type: 'md-unlock'},
                    {type: 'md-videocam'},
                    {type: 'md-volume-down'},
                    {type: 'md-volume-mute'},
                    {type: 'md-volume-off'},
                    {type: 'md-volume-up'},
                    {type: 'md-walk'},
                    {type: 'md-warning'},
                    {type: 'md-watch'},
                    {type: 'md-water'},
                    {type: 'md-wifi'},
                    {type: 'md-wine'},
                    {type: 'md-woman'}
                ],
                iconFontDatas: [
                    {type: 'icon iconfont icona'},
                    {type: 'icon iconfont icona1'},
                    {type: 'icon iconfont icona10'},
                    {type: 'icon iconfont icona2'},
                    {type: 'icon iconfont icona3'},
                    {type: 'icon iconfont icona4'},
                    {type: 'icon iconfont icona5'},
                    {type: 'icon iconfont icona6'},
                    {type: 'icon iconfont icona7'},
                    {type: 'icon iconfont icona8'},
                    {type: 'icon iconfont icona9'},
                    {type: 'icon iconfont iconbanben1'},
                    {type: 'icon iconfont iconbaobiaomoban'},
                    {type: 'icon iconfont iconbaocun1'},
                    {type: 'icon iconfont iconbaocunbingguanbi'},
                    {type: 'icon iconfont iconbiaoqian'},
                    {type: 'icon iconfont iconbtn-guize'},
                    {type: 'icon iconfont iconchexiao'},
                    {type: 'icon iconfont icondaochu'},
                    {type: 'icon iconfont icondaoru'},
                    {type: 'icon iconfont icondazhongzhou'},
                    {type: 'icon iconfont iconexcel'},
                    {type: 'icon iconfont iconexcel1'},
                    {type: 'icon iconfont iconexit-full-screen'},
                    {type: 'icon iconfont iconfenpei'},
                    {type: 'icon iconfont iconfinish'},
                    {type: 'icon iconfont iconfull-screen'},
                    {type: 'icon iconfont iconicon-test'},
                    {type: 'icon iconfont iconicon-test1'},
                    {type: 'icon iconfont iconicon-test10'},
                    {type: 'icon iconfont iconicon-test11'},
                    {type: 'icon iconfont iconicon-test12'},
                    {type: 'icon iconfont iconicon-test13'},
                    {type: 'icon iconfont iconicon-test14'},
                    {type: 'icon iconfont iconicon-test15'},
                    {type: 'icon iconfont iconicon-test2'},
                    {type: 'icon iconfont iconicon-test3'},
                    {type: 'icon iconfont iconicon-test4'},
                    {type: 'icon iconfont iconicon-test5'},
                    {type: 'icon iconfont iconicon-test6'},
                    {type: 'icon iconfont iconicon-test7'},
                    {type: 'icon iconfont iconicon-test8'},
                    {type: 'icon iconfont iconicon-test9'},
                    {type: 'icon iconfont iconjurassic_refuse-audit'},
                    {type: 'icon iconfont iconjurassic_reject-task'},
                    {type: 'icon iconfont iconlishibanben'},
                    {type: 'icon iconfont iconmenu-fold'},
                    {type: 'icon iconfont iconmenu-unfold'},
                    {type: 'icon iconfont iconnotification'},
                    {type: 'icon iconfont iconpdf'},
                    {type: 'icon iconfont iconPDF'},
                    {type: 'icon iconfont iconpdf1'},
                    {type: 'icon iconfont iconPPT'},
                    {type: 'icon iconfont iconquxiao'},
                    {type: 'icon iconfont iconradiobox'},
                    {type: 'icon iconfont iconrili1'},
                    {type: 'icon iconfont iconshengji'},
                    {type: 'icon iconfont iconshouquan'},
                    {type: 'icon iconfont iconweibiaoti11'},
                    {type: 'icon iconfont iconword'},
                    {type: 'icon iconfont iconWORD'},
                    {type: 'icon iconfont iconxingzhuanggongnengtubiao-'},
                    {type: 'icon iconfont iconxinjian1'},
                    {type: 'icon iconfont iconxintubiao-'},
                    {type: 'icon iconfont iconyichu'},
                    {type: 'icon iconfont iconyuyuetoubiao'},
                    {type: 'icon iconfont iconzhankai'},
                    {type: 'icon iconfont iconzhongzhi'},
                    {type: 'icon iconfont iconzhongzhi3'},
                    {type: 'icon iconfont iconzhuye'},
                    {type: 'icon iconfont iconzujian'},
                ],
                svgDatas: [
                    {
                        before: '#icona',
                        after: '#iconicon-test5'
                    },
                    {
                        before: '#icona2',
                        after: '#iconicon-test7'
                    },
                    {
                        before: '#icona10',
                        after: '#iconicon-test14'
                    },
                    {
                        before: '#icona1',
                        after: '#iconicon-test15'
                    },
                    {
                        before: '#icona8',
                        after: '#iconicon-test13'
                    },
                    {
                        before: '#icona9',
                        after: '#iconicon-test12'
                    },
                    {
                        before: '#icona3',
                        after: '#iconicon-test6'
                    },
                    {
                        before: '#icona4',
                        after: '#iconicon-test8'
                    },
                    {
                        before: '#icona5',
                        after: '#iconicon-test9'
                    },
                    {
                        before: '#icona7',
                        after: '#iconicon-test10'
                    },
                    {
                        before: '#icona6',
                        after: '#iconicon-test11'
                    },
                    { // 九院
                        before: '#icontrack',
                        after: ''
                    },
                    { // 九院
                        before: '#iconquestion',
                        after: ''
                    },
                    { // 九院
                        before: '#iconcooperate',
                        after: ''
                    },
                    { // 九院
                        before: '#iconrizhi',
                        after: ''
                    }
                ]
            }
        },
        props: {
            showValue: {
                type: Object,
                default () {
                    return {
                        model: 'icon',
                        type: '',
                        before: '',
                        after: ''
                    };
                }
            },
            disabled: {
                type: Boolean,
                default: false
            },
            transfer: {
                type: Boolean,
                default: false
            }
        },
        watch: {
            showValue : {
                deep: true,
                handler(){
                    this.model = this.showValue.model
                    if (this.model === 'svg') {
                        this.selectItem = [
                            {
                                before: this.showValue.before,
                                after: this.showValue.after
                            }
                        ]
                    } else {
                        this.selectItem = [
                            {
                                type: this.showValue.type,
                            }
                        ]
                    }
                }
            }
        },
        created() {
            this.model = this.showValue.model
            if (this.model === 'svg') {
                this.selectItem = [
                    {
                        before: this.showValue.before,
                        after: this.showValue.after
                    }
                ]
            } else {
                this.selectItem = [
                    {
                        type: this.showValue.type,
                    }
                ]
            }
        },
        methods: {
            onClick (name) {
                this.selectItem = [];
                this.items.forEach((item) => {
                    if (name === item.name ) {
                        this.model = item.value
                    }
                })
            },
            selectClick (item) {
                this.selectItem = [];
                this.selectItem.push(item)
                if (this.model === 'svg') {
                    this.$emit('on-select-click', this.model, item.before, item.after)
                } else {
                    this.$emit('on-select-click', this.model, item.type)
                }
            }
        }
    }
</script>
<style lang="less">
</style>
